version: '2'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        volumes:
        - './postgres_data:/var/lib/postgresql/data'
        environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        ports:
        - ${DEPLOYMENT_POSTGRES_DB_PORT}:5432
    vector_store:
        image: chromadb/chroma
        volumes:
          - ./chroma_data:/chroma/.chroma/index
        ports:
          - ${DEPLOYMENT_CHROMA_DB_PORT}:8000
